INSERT INTO CRYPTO_ANALYSIS_DB.GOLD.CRYPTO_ANALYSIS 
SELECT * FROM CRYPTO_ANALYSIS_DB.GOLD.CRYPTO_ANALYSIS_HIST WHERE DATE(LOAD_DTM) = DATE(SYSDATE());

SELECT * FROM CRYPTO_ANALYSIS_DB.GOLD.CRYPTO_ANALYSIS;