CREATE OR REPLACE DATABASE CRYPTO_ANALYSIS_DB;

CREATE OR REPLACE SCHEMA CRYPTO_ANALYSIS_DB.GOLD;

CREATE OR REPLACE TABLE CRYPTO_ANALYSIS_DB.GOLD.CRYPTO_ANALYSIS_HIST (
    SYMBOL VARCHAR(20) NOT NULL, 
    COIN_NAME VARCHAR(50),
    PRICE NUMBER(18, 4) NOT NULL,
    COIN_RANK NUMBER(6),
    RISK_CATEGORY VARCHAR(50),
    TOTAL_DAILY_SCORE NUMBER(10),
    TRADE_SIGNAL VARCHAR(100),
    TOP_HEADLINE VARCHAR(3000),
    VOLUME_24H NUMBER(20),
    PERCENT_CHANGE_1H NUMBER(10, 2),
    PERCENT_CHANGE_24H NUMBER(10, 2),
    PERCENT_CHANGE_7D NUMBER(10, 2),
    MARKET_TS TIMESTAMP_NTZ,
    MARKET_DATE DATE,
    NEWS_DATE DATE,
    LOAD_DTM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL, MARKET_DATE)
);

CREATE TABLE CRYPTO_ANALYSIS AS 
SELECT * FROM CRYPTO_ANALYSIS_HIST WHERE 1 = 2;

SELECT * FROM CRYPTO_ANALYSIS_DB.GOLD.CRYPTO_ANALYSIS;

DESCRIBE TABLE CRYPTO_ANALYSIS;