CREATE OR REPLACE SCHEMA CRYPTO_ANALYSIS_DB.SILVER;

CREATE OR REPLACE TABLE CRYPTO_ANALYSIS_DB.SILVER.CRYPTO_NEWS (
    SYMBOL            VARCHAR(20) NOT NULL,
    COIN_NAME         VARCHAR(100),
    NEWS_HEADLINE     VARCHAR(5000),
    PREDICTION        VARCHAR(50),
    NEWS_TIMESTAMP    TIMESTAMP_NTZ,
    NEWS_DATE         DATE,
    SENTIMENT_SCORE   NUMBER(5,0) NOT NULL,
    LOAD_DTM          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SYMBOL, NEWS_TIMESTAMP)
);


SELECT * FROM CRYPTO_ANALYSIS_DB.SILVER.CRYPTO_NEWS;

CREATE OR REPLACE TABLE CRYPTO_ANALYSIS_DB.SILVER.CRYPTO_PRICE (
    SYMBOL               VARCHAR(20),
    PRICE                NUMBER(18, 6),
    COIN_RANK             NUMBER(6),
    VOLUME_24H            NUMBER(20, 0),
    PERCENT_CHANGE_1H     NUMBER(10, 2),
    PERCENT_CHANGE_24H    NUMBER(10, 2),
    PERCENT_CHANGE_7D     NUMBER(10, 2),
    MARKET_TIMESTAMP      TIMESTAMP_NTZ,
    INGESTED_AT           TIMESTAMP_NTZ,
    MARKET_DATE           DATE,
    RISK_CATEGORY         VARCHAR(50),
    LOAD_DTM              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


SELECT * FROM CRYPTO_ANALYSIS_DB.SILVER.CRYPTO_PRICE;